config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :blurbs

  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  
  map.connect '/scj.htm', :controller => 'redirect', :url => '/people/15'
  map.connect '/index.php/Principal_Investigator', :controller => 'redirect', :url => '/people/15'
  map.connect '/index.php/People', :controller => 'redirect', :url => '/people'
  map.connect '/index.php/Rhesus_Brain_Atlas', :controller => 'redirect', :url => '/pages/2'
  map.connect '/index.php/Research', :controller => 'redirect', :url => '/about/research_objectives'
  map.connect '/index.php/Employment', :controller => 'redirect', :url => '/opportunites/researchers'
  map.connect '/opportunities/employment.html', :controller => 'redirect', :url => '/opportunites/researchers'
  map.connect '/index.php/Publications', :controller => 'redirect', :url => '/publications'
  map.connect '/publications.html', :controller => 'redirect', :url => '/publications'
  map.connect '/index.php/Neuropsychology_Neuroimaging_Lab', :controller => 'redirect'
  map.connect '/index.php/:title', :controller => 'redirect'

  map.collaborators 'people/collaborators', :controller => 'people', :action => 'collaborators'
  map.current_studies 'about/current_studies', :controller => 'application', :action => 'current_studies'
  map.research_objectives 'about/research_objectives', :controller => 'application', :action => 'research_objectives'
  map.opportunities 'opportunities/:opportunity_type', :controller => 'job_advertisements', :action => 'index'
  map.contact 'contact', :controller => 'contact', :action => 'index'
  
  map.signup '/signup', :controller => 'users', :action => 'new'
  
  map.resources :users

  map.resource :session

  map.resources :pages
  
  map.resources :authorships
 
  map.resources :study_descriptions
  
  map.resources :events

  map.resources :job_advertisements

  map.resources :publications

  map.resources :personnel_groups

  map.resources :addresses

  map.resources :people
    
  map.root :controller => 'application', :action => 'index'

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
  map.permalinked_pages '/:permalink.:format', :controller => 'pages', :action => 'show'
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  include ActionView::Helpers::TextHelper

  default_scope :order => 'publication_date DESC'
  
  
  has_many :authorships
  has_many :people, :through => :authorships
  
  validates_presence_of :title, :authors_info
  
  has_attached_file :pubfile
  validates_attachment_size :pubfile, :less_than => 50.megabytes
  validates_attachment_content_type :pubfile, :content_type => ['application/pdf']
    
  def pubmed_link
    "http://www.ncbi.nlm.nih.gov/pubmed/#{pmid}"
  end
  
  def doi_link
    "http://dx.doi.org/#{doi}"
  end
  
  def year
    publication_date.blank? ? DateTime.current.beginning_of_year : publication_date.beginning_of_year 
  end
  
  def publication_or_inpress_date
    publication_date.blank? ? DateTime.now : publication_date
  end
  
  def abridged_abstract(n = 1)
    "#{abstract.split('. ').first(n).join('. ')}."
  end
  
  def contributer_publications
    contributer_publications = Set.new
    people.each do |person|
      person.publications.each do |pub|
        contributer_publications << pub unless (person.full_name == "Sterling Johnson" or pub == self)
      end
    end
    
    return contributer_publications
  end
  
  def to_param
    "#{id}-#{title.gsub(" ", "-")[0..30]}"
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_filter :set_active_tab
  
  def set_active_tab
    @active_nav_tab = 'pubs-tab'
  end
  
  # GET /publications
  # GET /publications.xml
  def index
    @publications = Publication.all
    
    # Don't need to explicitly respond, so that the rss builder can be used.
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.xml  { render :xml => @publications }
    # end
  end

  # GET /publications/1
  # GET /publications/1.xml
  def show
    @all_publications = Publication.all
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.xml
  def new
    @publication = Publication.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
  end

  # POST /publications
  # POST /publications.xml
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        flash[:notice] = 'Publication was successfully created.'
        format.html { redirect_to(@publication) }
        format.xml  { render :xml => @publication, :status => :created, :location => @publication }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @publication.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.xml
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        flash[:notice] = 'Publication was successfully updated.'
        format.html { redirect_to(@publication) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @publication.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.xml
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to(publications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_new_edit.html.erb
<% form_for(@publication, :html => {:multipart => true}) do |f| %>
  <%= f.error_messages %>
  <div style="float:left;">
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      	<%= f.label :journal_info %><br />
		<span style="font-size:smaller; color:gray;">
			Standard format: Journal Title. Publication date; Volume #(Issue #):pages.<br />
			For publications without an established publication date,<br />
			the publication date may be replaced with the current status<br /> 
			of the publication (e.g., In Press)<br />
		</span>
      	<%= f.text_field :journal_info %>
    </p>
  	<p>
  		<%= f.label :authors_info %><br />
  		<span style="font-size:smaller; color:gray;">
			Copy the authors list from the pubmed citation<br />
		</span>
  		<%= f.text_area :authors_info %>
  	</p>
    <p>
      	<%= f.label :abstract %><br />
      	<%= f.text_area :abstract %>
    </p>
    <p>
      	<%= f.label :publication_date %><br />
		<span style="font-size:smaller; color:gray;">
			Unknown fields may be left blank<br />
		</span>
      	<%= f.date_select :publication_date, :start_year => 2000, :end_year => 2020, :include_blank => true %>
    </p>
    <p>
      	<%= f.label :pmid %><br />
      	<%= f.text_field :pmid %>
    </p>
    <p>
      	<%= f.label :doi, "DOI" %><br />
      	<%= f.text_field :doi %>
    </p>
		<p>
			<%= f.label :pubfile, "Upload a PDF" %><br />
			<%= f.file_field :pubfile %>
		</p>
  </div>
  <div style="float:left; margin-left:200px;">
    <h3>Contributors:</h3>
    <span style="font-size:smaller; color:gray;">
		Check any people that are co-authors
	</span>
    <p>
  	  <!-- products/_form.rhtml -->
      <% for contributor in Person.find(:all, :order => :last_name) %>
        <%= check_box_tag "publication[person_ids][]", contributor.id, @publication.people.include?(contributor) %>
        <%= contributor.last_name_first %><br />
      <% end %>
    </p>
  </div>
  <br style="clear:both">
  <p>
    <%= f.submit action %>
  </p>
<% end %>

app/views/publications/edit.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'publications' %>
<% end %>

<% @page_title = title("Edit publication - " + @publication.title) %>

<h1>Editing publication</h1>

<%= render :partial => 'new_edit', :locals => { :action => 'Update' } %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'publications' %>
	<%= auto_discovery_link_tag :rss, :format => :rss %>
<% end %>

<% @page_title = title("Peer Reviewed Publications") %>

<div id="pubs-banner" class="banner-row">
	<h2>Publications from the WADRC Imaging Lab and Collaborators</h2>
</div>

<div id="greeting-and-links">
	<h2>Publication years</h2>
	<ul>
		<% @publications.reverse.group_by(&:year).each do |year, pubs| %>
			<li><%= link_to year.year, "##{year.year}-section" %></li>
		<% end %>
	</ul>
</div>
<hr class='yellow-hr'></hr>

<div id="pubs-index">
	<% @publications.group_by(&:year).each do |year, pubs| %>
		<div class="section-header">
			<a name="<%= year.year.to_s + '-section' %>"></a>
			<h3><%= year.year %></h3>
			<div class="divider">
				<div class="upbutton"><%= link_to 'top', '#top-of-page' %></div>
				<hr class="gray"></hr>
			</div>
		</div>
		<ul id="pubs-list">
			<% pubs.sort_by { |pub| pub.publication_date || DateTime.current }.reverse.each_with_index do |pub, i| %>
				<% pubid = "pub-#{pub.id}" %>
				<% pubtog = "#{pubid}-tog" %>
				<% if i % 3 == 0 %>
					<div class="row" style="overflow:visible; width:100%; clear:both;">
				<% end %>
				<li class="pub">
					<h3 class="pub-title"><%= link_to pub.title, pub %></h3>
					<p class="pub-authors"><%= pub.authors_info %></p>
					<p class="pub-journal"><%= pub.journal_info %></p>
					<div class="abstract" style="<%= i % 3 == 2 ? 'right:0;margin-top:-17px;' : 'left:0;' %>">
						<h3>Abstract</h3>
						<% if pub.abstract.nil? %>
							<p>No abstract available.</p>
						<% else %>
							<%#= image_tag(pub.figure.url(:small), :class => 'pub-figure') unless pub.figure.nil? %>
							<p>
								<%= pub.abridged_abstract 2 %>..
								<%= link_to '[read more]', pub %>
							</p>
						<% end %>
						<p class="pub-footer">
							<% if logged_in? %>
					    	<%= link_to 'edit', edit_publication_path(pub) %>
					    	<%= link_to 'delete', pub, :confirm => 'Are you sure?', :method => :delete %>
							<% end %>
							<%= link_to '[pubmed]', pub.pubmed_link unless pub.pmid.nil? %>
						</p>
					</div>
				</li>
				<% if i % 3 == 2 && i != 0 %>
					</div>
				<% end %>
			<% end %>
		</ul>
		<br style="clear:both"></br>
	<% end %>
	<%= link_to image_tag('feed-icon-28x28.png', :size => '28x28'), formatted_publications_url(:rss) %>
</div>

<p>
	<% if logged_in? %>
		<%= link_to 'New publication', new_publication_path %>
	<% end %>
</p>

app/views/publications/new.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'publications' %>
<% end %>

<% @page_title = title("Create a new publication") %>

<h1>New publication</h1>

<%= render :partial => 'new_edit', :locals => { :action => 'Create' } %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'publications' %>
<% end %>
<% @page_title = title("Publication - " + @publication.title) %>

<div id="pubs-banner" class="banner-row">
	<h2>Publications from the WADRC Imaging Lab and Collaborators</h2>
</div>

<br />

<div id="pubs-show-sidebar" class="publications-list">
	<h3>Other Publications by These Authors:</h3>
	<ul id="list-of-related-pubs" class="link-and-subtext">
		<% related_publications = @publication.contributer_publications.empty?  ? @all_publications : @publication.contributer_publications %>
		<%# for pub in related_publications.sort_by(&:publication_date).reverse.first(10) %>
		<% for pub in related_publications.sort_by { |pub| pub.publication_date || DateTime.current }.reverse.first(10) %>
			<li>
				<%= link_to pub.title, pub %> 
				<p> <%=h pub.publication_date.blank? ? "In Press" : pub.publication_date.to_s(:long) %></p>
			</li>
		<% end %>
	</ul>
	<p><%= link_to 'back to the list of publications...', publications_path %></p>
</div>

<div id="pub-show-info">
	<h3 class="title"><%=h @publication.title %></h3>
	<hr class="blue" style="clear:none;" />
	<p class="authors"><%=h @publication.authors_info %></p>
	<p class="journal"><%=h @publication.journal_info %></p>
	<h3>Abstract</h3>
	<p class="abstract">
		<% if @publication.abstract.nil? %>
			No abstract available.
		<% else %>
			<%=h @publication.abstract %>
		<% end %>
	</p>
	<p class="pubmed-link">Pubmed ID:
		<% if @publication.pmid.blank? %>
			Not Available
		<% else %>
			<%= link_to(@publication.pmid, @publication.pubmed_link) %>
		<% end %>
	</p>
	<p class="pubmed-link">DOI:
		<% if @publication.doi.blank? %>
			Not Available
		<% else %>
			<%= link_to(@publication.doi, @publication.doi_link) %>
		<% end %>
	</p>
	<p>
		<%= link_to("PDF", @publication.pubfile.url, :class => "pdflink") if @publication.pubfile.exists? %>
	</p>
	<h3>Contributing Lab Members</h3>
	<ul id="contributor-list">
		<% for person in @publication.people %>
			<li class="contributor-link"><%= link_to person.full_name, person %></li>
		<% end %>
	</ul>
	<p>
		<% if logged_in? %>
			<%= link_to 'Edit', edit_publication_path(@publication) %> |
			<%= link_to 'Delete', @publication, :confirm => 'Are you sure?', :method => :delete %>
		<% end %>
	</p>
</div>